---
version: "3"
services:
  app:
    build: .
    ports:
      - 8008:8008
    volumes:
      - /var/lib/firecracker:/var/lib/firecracker
      - /run/containerd/containerd.sock:/run/containerd/containerd.sock
